### ISSUE TITLE
FarCry 7 Installation error

### ISSUE THREAD

**Issue by asimakos** [farcrycore/core#100]
Hello!
I have downloaded and tried to install FarCry 7 (latest version - chelsea theme) according to [Installation Guide](https://discourse.farcrycore.org/t/farcry-7-installation-guide/119). I have used Lucee Server 5.2.9 via Commandbox environment and MySQL 5.6.
At the end of my installation (password not mentioned), i get the appropriate successful message
 
![farcry4](https://user-images.githubusercontent.com/15226087/116982946-22affa80-acd2-11eb-97c9-3595278ebf9f.png)
but afterwards when i try to visit both login and view site links, i receive the following screenshots:

![farcry7](https://user-images.githubusercontent.com/15226087/116983136-673b9600-acd2-11eb-82a9-6c6050b8a6a3.png)

![farcry8](https://user-images.githubusercontent.com/15226087/116983159-6efb3a80-acd2-11eb-8420-18d90edc9b5d.png)

Any idea that could help me?

Regards

**Comment by justincarter** [comment]
For some reason the "farcryConstructor.cfm" has a section of code that should be there, the "developer specific constructor" block near the end of the file that has an if statement and an include.

You should be able to edit the file and remove those few lines of code, like the removed lines in this commit;

https://github.com/farcrycore/project-chelsea/commit/bb5cc0403a128661bf7f51f3d55bfaea3abb13ab#diff-c84d93a7b5afb230c6933321454386a4da437741b93195645deece4d8bf7eb31

If you make that change it should resolve the problem.

**Comment by asimakos** [comment]
Thanks for your reply!

I followed your instructions carefully! Unfortunately i have got a slight issue with View site, Login looks good.

![app1](https://user-images.githubusercontent.com/15226087/116999224-fc955500-ace7-11eb-9690-6aeaecd8ef7c.png)

![app2](https://user-images.githubusercontent.com/15226087/116999263-0cad3480-ace8-11eb-972f-e162e9aa52b4.png)

Any idea that could help me?

Regards

**Comment by justincarter** [comment]
If you try adding `?debug=1` to the URL the 404 page will know that you're running locally and give you some more details.

I'm guessing there might be an issue with the default site tree for some reason. If you can log in to the Webtop, go to the Site tab and see if you can preview the home page from there. If it's in Draft mode then it would need to be Approved before it's visible to anonymous users.

**Comment by asimakos** [comment]
I append ?debug=1 to the URL and i receive the following

![page1](https://user-images.githubusercontent.com/15226087/117005126-8b59a000-acef-11eb-8c2e-7ad24af504a7.png)

in Webtop, Site Tab everything is approved and still 404 page
![page2](https://user-images.githubusercontent.com/15226087/117005267-b643f400-acef-11eb-89f3-8680742863d6.png)

For your convenience, i could email you the project if there is no problem.

Regards

**Comment by seancoyne** [comment]
Sounds like you need to run the Fix RefObjects utility the webtop admin.

**Comment by justincarter** [comment]
Ok, I think I know the issue. The installer is supposed to trigger a process that populates the "refobjects" table, but it didn't run because of the first error you got that was blocking application startup.

If you log in to the Webtop and go to the Admin tab, Developer Tools, then Fix Refobjects, you should be able to fix missing refobjects with that tool (I think the default checked items is enough).

**Comment by asimakos** [comment]
In my Webtop screen, i click this menu item and everything will be fine(?) 

![repair](https://user-images.githubusercontent.com/15226087/117007289-23588900-acf2-11eb-8369-17fa6f9ca1e6.png)

Thanks a lot for your assistance!!!

**Comment by justincarter** [comment]
Excellent, glad you got it working :)
